anchor_version = "0.20.1"
solana_version = "1.9.5"

[programs.localnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[programs.devnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[programs.mainnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/vsrkfNVoSkxmTEg1kYN5w2Kbe1wLuTTxumh5ofAKLaS.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
