anchor_version = "0.24.2"
solana_version = "1.9.5"

[programs.localnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[programs.devnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[programs.mainnet]
voter_stake_registry = "vsr2nfGVNHmSY8uxoBGqq8AQbwz3JwaEaHqGbsTPXqQ"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[workspace]
members = ["programs/voter-stake-registry"]